development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/1




#  adapter: redis
#  url: <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: qna_production
