development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:4c04a08a24ee46b9e01f14195b3b5c7a@tarpon.redistogo.com:9003/
  channel_prefix: qna_production

